### ISSUE TITLE
`jython: command not found` on Windows-Powershell

### ISSUE THREAD

**Issue by LukeSavefrogs** [LukeSavefrogs/setup-jython#8]
On **Windows** runners, the `jython` command is recognised **only** when the job `shell` is set to `bash`, but **fails** when set to `cmd` or `pwsh`

**Comment by LukeSavefrogs** [comment]
> This will add `C:\Users\runneradmin/.local/bin`, which is recognized by PowerShell but not bash.

Seems great!
Think you can provide a separate PR with only these changes?

I would like to postpone the Java PR for now, and this seems like a very quick and easy fix on your part😄 
Maybe uncomment tests on powershell in the Github Action and let's see what happens...

**Comment by ZZy979** [comment]
OK, I'm working on it.

But there is another problem: the job "Run Jython (Bash)" also failed for version 2.0/2.1 on Windows because of "ClassNotFoundException: org.python.util.jython".

![image](https://github.com/LukeSavefrogs/setup-jython/assets/32253183/74d5b9cd-7036-483c-9d14-9c3a53345c39)

It may be caused by the wrong classpath separator, which should be ":" on Linux and ";" on Windows. As it seems that ":$CLASSPATH" is unnecesary, simply deleting it may help.

![image](https://github.com/LukeSavefrogs/setup-jython/assets/32253183/5309a7f4-1dfe-4153-bce8-4ecf4ceebe46)
